name: CI

on:
  pull_request:
  push:
    branches:
      - dev

jobs:
  build_test:
    name: 🚴 Build + Lint + Test 🚴  # Match the name below (8398a7/action-slack).
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@v4
        with:
          node-version: '17.x'
          cache: 'yarn'

      - name: 🤞 Install dependencies 🧪
        run: yarn install --frozen-lockfile --prefer-offline

      - name: 🤞 Run Lint 🧪
        run: yarn lint

      - name: 🤞 Run Test 🧪
        run: yarn test --passWithNoTests

      - name: 🤞 Run Build 🧪
        run: yarn build
        env:
          APP_SENTRY_DSN: 'https://random-token@sentry.io'
          APP_SENTRY_TRACES_SAMPLE_RATE: 0.2
          APP_ENVIRONMENT: 'ci'
          GRAPHQL_CODEGEN_ENDPOINT: 'https://random-domain.com/graphql/'
          APP_GRAPHQL_ENDPOINT: 'https://random-domain.com/graphql/'
          APP_MAPSWIPE_WEBSITE: 'https://random-website-domain.com'
